name: momease
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  meta: ^1.11.0
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/article/
    - assets/images/community/
    - assets/images/exercise/
    - assets/images/therapy/
    # Add assets from the json_data directory to the application.
    - assets/json_data/
